export const GET_CONTACTOS = "GET_CONTACTOS"
export const DEL_CONTACTOS = 'DEL_CONTACTOS'
export const POST_CONTACTOS = 'POST_CONTACTOS'
export const GET_CONTACTOS_ID = "GET_CONTACTOS_ID"
export const PUT_CONTACTOS = "PUT_CONTACTOS"
export const POST_USUARIOS= "POST_USUARIOS"